mkdir assignment/model
mkdir assignment/model/user
mkdir assignment/model/website
mkdir assignment/model/page
mkdir assignment/model/widget 
touch assignment/model/models.server.js
touch assignment/model/user/user.schema.server.js
touch assignment/model/user/user.model.server.js
touch assignment/model/website/website.schema.server.js
touch assignment/model/website/website.model.server.js
touch assignment/model/page/page.schema.server.js
touch assignment/model/page/page.model.server.js
touch assignment/model/widget/widget.schema.server.js
touch assignment/model/widget/widget.model.server.js
